name: Run bitly_cookies.py Every Hour

on:
  schedule:
    - cron: '0 * * * *'   # Every hour (UTC)
  workflow_dispatch:        # Optional: allows manual runs from the Actions tab

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # You can change this if you use another version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run bitly_cookies.py and log output
        run: |
          mkdir -p logs
          python bitly_cookies.py >> logs/run_$(date -u +"%Y-%m-%d_%H-%M-%S").log 2>&1
          echo "✅ Script executed at $(date -u)" >> logs/history.log
